# needed for deployment
version: '3'

services:
  app:
    container_name: tspace
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "10020:80"